dist: xenial
sudo: required  # Use the new travis docker based infrastructure
services:
  - docker
git:
  depth: 99999
language: python
python:
- '3.6'
jobs:
  include:
    - stage: test
      script: 
        - pip install pylint
        - ./check-code.sh || travis_terminate 1
    - stage: deploy
      if: (branch = master OR (tag = branch)) AND type = push
      script:
        - export CONFIG_TAG=$(git describe --tags | awk -F'[-.]' '{if ($4!="" && $5!="") print $1"."$2"."$3+1"-unstable."$4"."$5; else print $1"."$2"."$3;}')
        - docker build -t csiroeasi/easi-config:$CONFIG_TAG -t csiroeasi/easi-config:latest .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push csiroeasi/easi-config:$CONFIG_TAG
        - docker push csiroeasi/easi-config:latest
# notifications:
#   slack:
#     secure: 
